### PR TITLE
disable preopt only on pixel 3,3a,xl

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: anupritaisno1 <www.anuprita804@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
@paintedman I have tested this on pixel 4. Can you test on 4xl?

**Comment by thestinger** [comment]
I'm not sure if this is an issue for the Pixel 2 and 2 XL.

**Comment by ghost** [comment]
We should also try nostripping instead of true for dexpreopt on pixel 3. Maybe it will work and then we might know where the problem may be

**Comment by thestinger** [comment]
That may just mask the problem because it will let it fall back to compiling code if the precompiled code doesn't work.

**Comment by thestinger** [comment]
Also note a lot of hardening that used to be present for this stuff is not present, i.e. stopping ART from trying to use dalvik-cache code, getting rid of the non-code compiled images, etc.

**Pull request closed without merging**
