### PR TITLE
Add initial bullhead API-26 naked config

### PR DESCRIPTION
**Pull request by hagau**
This still includes libraries for face detection and device managment.
dep-dso-proprietary-blobs-api26.txt is unedited copy of the API-25 version.

### CODE REVIEW

**Comment by thestinger** [comment]
@hagau It's probably better to submit it directly to https://github.com/anestisb/android-prepare-vendor FWIW.

**Comment by thestinger** [comment]
I had to rebase this and you'll need to cherry-pick it back on top of the current master here.

**Comment by hagau** [comment]
Upstream already has a cleaner patch.

**Comment by thestinger** [comment]
Ah, okay.

**Pull request closed without merging**
